### ISSUE TITLE
Not recording landings

### ISSUE THREAD

**Issue by PadinnPlays** [DCS-gRPC/lso#7]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I've noticed since the Multithreaded update on the 18th my DCS server does not seem to be recording landings anymore. I've confirmed gRPC is working and it shows connected in the LSO Terminal. I'm not quite sure what happened, where can I start trouble shooting?

**Comment by rkusa** [comment]
Thanks for the report. I haven't tried it with the MT update myself yet. The next steps would be to start the LSO with the `-vv` argument to get debug logs and look for things that are off. Or share the logs or an excerpt of them here. The other option would be to wait until I found the time to try to reproduce it, but I am unfortunately a bit busy right now so it could take a while.

**Comment by PadinnPlays** [comment]
I was able to get it working again and it was an issue with my setup. I
used a bat file provided on the grpc discord. If you need any help testing
new features in the future feel free to contact me, we love this tool for
training!
